### ISSUE TITLE
Grant Privileges via YAML

### ISSUE THREAD

**Issue by bendhouseart** [bendhouseart/mysql_scripts#3]
Add functionality so that an administrator can pass a yaml of the form:
```yaml
username: username
  database: database
  permissions: SELECT 
    tabels:
      - table1
      - table2
      - eg eg
```
to some function and grant users permissions on one set of tables from a singular database.
